- name: Install the cman config file
  template:
    src: "{{cman_config_template}}"
    dest: /etc/cluster/cluster.conf

- name: Install the Corosync key
  copy:
    src: "{{corosync_key}}"
    dest: /etc/corosync/authkey
