---
- hosts: all
  pre_tasks:
    - name: Installing MySQL repository.
      yum: name=http://repo.mysql.com/mysql-community-release-el6-5.noarch.rpm state=present
  roles:
    - { role: geerlingguy.mysql,
        mysql_root_password_update: yes,
        mysql_enabled_on_startup: no,
        mysql_max_binlog_size: "100M",
        mysql_expire_logs_days: "10" }
    - { role: mysql_semisync,
        mysql_replication_user: {
          name: "{{replication_user}}",
          password: "{{replication_password}}",
          host: "%",
          priv: "*.*:SELECT,REPLICATION CLIENT,REPLICATION SLAVE,PROCESS,SUPER,RELOAD" }}
